const fs=require('fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const html=fs.readFileSync('index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
const dom=new JSDOM(html,{url:'https://crm.example.invalid/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window,d=w.document;w.matchMedia=()=>({matches:false,addEventListener(){},addListener(){}});w.confirm=()=>true;w.alert=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLElement.prototype.scrollTo=function(){};w.scrollTo=()=>{};w.Chart=function(){this.destroy=()=>{}};
for(const f of ['app-core-01.js','app-core-02a.js','app-core-02b.js','app-core-03.js','app-core-04.js','app-core-05.js','app-core-06.js','app-core-07.js'])require('vm').runInContext(fs.readFileSync(f,'utf8').replace('\ninitResponsiveShell();','\n'),dom.getInternalVMContext());
const run=s=>require('vm').runInContext(s,dom.getInternalVMContext()),value=(id,v)=>{const el=d.getElementById(id);assert(el,'Missing field '+id);el.value=v;};
run(fs.readFileSync('tests/fixtures.js','utf8').replace('__ROLE__','admin').replace("actualizarSidebarSesion();updateRolUI();navigate('clientes');",''));
for(const f of ['app-workflow.js','app-prospect-workflow.js','app-contract-word.js'])run(fs.readFileSync(f,'utf8'));
run("actualizarSidebarSesion();navigate('clientes')");
assert(d.getElementById('nav-admin-section').hidden);
const headers=[...d.querySelectorAll('#main-content th')].map(e=>e.textContent.trim());assert(headers.slice(4,11).join('|').startsWith('Registro ↓|Nombre ⇅|Teléfono|Servicio ⇅|Etapa ⇅|Fecha de solicitud|Documentos'),headers);assert(!headers.includes('Fuente'));
run("navigate('cuenta')");assert(d.body.textContent.includes('Crear cuenta técnica'));run('abrirAltaTecnica()');assert.equal(d.getElementById('as-rol').value,'tech_admin');run("closeModal('modal-asesor')");
run("navigate('configuracion')");assert(!d.getElementById('cfg-nombre'),'Ordinary admin can render global settings');
run("navigate('leads');openModalLead('test-lead')");assert(d.body.textContent.includes('¿Cotiza actualmente ante el IMSS?'));assert(d.getElementById('lead-initial-criteria').textContent.includes('Cumple criterios iniciales'));
value('lead-servicio','asesoria_pension');run('onLeadServicioChange()');assert(d.body.textContent.includes('¿Cuenta con conservación de derechos?'));value('lead-el-semanas','900');value('lead-el-ley','97');value('lead-el-fecha-nac','09/09/1966');run('actualizarElegibilidadInicial()');assert(d.getElementById('lead-initial-criteria').textContent.includes('Cumple criterios iniciales'));
value('lead-servicio','retiro_desempleo');run('onLeadServicioChange()');assert.equal(d.getElementById('lead-el-semanas').value,'106');run("closeModal('modal-lead');openModalLead('test-lead')");assert(!run("store.leads[0].elegibilidad.porServicio"),'Cancelled draft mutated stored lead');
run("closeModal('modal-lead');archivadosLeadsAbiertos=true;renderPage('leads');toggleArchiveGroup('temporal')");assert(d.querySelector('[data-group="temporal"]').nextElementSibling.hidden);
run("navigate('clientes');editCliente('test-client')");assert.equal(d.getElementById('fc-fecha-registro').value,'01/08/2026');assert.equal(d.getElementById('fc-afore').value,'SURA');assert(d.getElementById('fc-rfc').closest('details'));value('fc-fecha-alta','20/08/2026');
(async()=>{
 await run('guardarCliente()');assert.equal(run('store.clientes[0].fechaAltaAfore'),'2026-08-20');assert.equal(run('store.agenda[0].fecha'),'2026-10-04');
 const stageBefore=run('store.clientes[0].etapa');let advance=run("avanzarEtapa('test-client')");assert(d.getElementById('modal-confirmar-firma'));run('resolverConfirmacionFirma(false)');await advance;assert.equal(run('store.clientes[0].etapa'),stageBefore);
 advance=run("avanzarEtapa('test-client')");value('confirmacion-firma-fecha','05/09/2026');run('resolverConfirmacionFirma(true,true)');await advance;assert.equal(run('store.clientes[0].etapa'),'contrato_firmado');assert.equal(run('store.clientes[0].fechaFirmaContrato'),'2026-09-05');assert.equal(run('store.clientes[0].firmaConfirmadaPorId'),'test-owner');
 run("privateContractTemplate={defaults:{empresa_representante:'REPRESENTANTE DE PRUEBA',empresa_domicilio:'DOMICILIO EMPRESARIAL DE PRUEBA',ciudad_contrato:'CIUDAD DE PRUEBA'}}");run("navigate('contratos');selectedClienteId='test-client';onContratoClienteChange()");assert.equal(d.getElementById('ct-honorarios').value,'8000');assert.equal(d.getElementById('ct-pagare-monto').value,'13000');assert.equal(d.getElementById('ct-fecha').type,'text');
 assert.equal(run('datosContratoWord().CLIENTE_NOMBRE'),'CLIENTE DE PRUEBA');
 run("sesionActiva.rol='tech_admin';actualizarSidebarSesion();navigate('configuracion')");assert(d.getElementById('cfg-nombre'));assert(!d.getElementById('nav-admin-section').hidden);
 run("sesionActiva.rol='asesor';actualizarSidebarSesion();navigate('cuenta')");assert(!d.body.textContent.includes('Crear cuenta técnica'));assert(d.getElementById('account-photo-file'));
 assert.deepEqual(errors,[]);console.log('PASS: DOM navigation and role separation, bootstrap form, dynamic criteria drafts, independent archives, real dates/reminder, signature cancel and save, manual contract fees.');dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
