const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const {JSDOM}=require('jsdom');const dom=new JSDOM(fs.readFileSync('index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''),{url:'https://example.invalid',runScripts:'outside-only'});const w=dom.window,d=w.document;const run=s=>vm.runInContext(s,dom.getInternalVMContext());w.matchMedia=()=>({matches:false,addEventListener(){},addListener(){}});w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLElement.prototype.scrollTo=function(){};w.scrollTo=()=>{};w.Chart=function(){};
for(const file of ['app-core-01.js','app-core-02a.js','app-core-02b.js','app-core-03.js','app-core-04.js','app-core-05.js','app-core-06.js','app-core-07.js'])run(fs.readFileSync(file,'utf8').replace('\ninitResponsiveShell();','\n'));
run(fs.readFileSync('tests/fixtures.js','utf8').replace('__ROLE__','admin').replace("actualizarSidebarSesion();updateRolUI();navigate('clientes');",''));for(const file of ['app-workflow.js','app-prospect-workflow.js','app-contract-word.js','app-operations.js'])run(fs.readFileSync(file,'utf8'));
(async()=>{
run("editCliente('test-client');editCliente('test-client')");for(const id of ['fc-fecha-alta','fc-afore','fc-fecha-firma','fc-fecha-biometrica'])assert.equal(d.querySelectorAll('#'+id).length,1,id);assert(d.getElementById('tab-cita-afore').contains(d.getElementById('fc-afore')));assert(d.getElementById('tab-contratos-alta').contains(d.getElementById('fc-fecha-alta')));
run("setVal('fc-banco','BBVA');actualizarNivelBBVA();setVal('fc-nivel-bbva','4');setVal('fc-hora-afore','14:30');setVal('fc-fecha-biometrica',fechaISOaMX(sumarDiasISO(fechaISOLocal(new Date()),1)))");assert(!d.getElementById('bbva-level-wrap').hidden);assert(d.getElementById('fc-clabe').closest('.form-group').hidden);await run('guardarCliente()');assert.equal(run('store.clientes[0].nivelCuentaBBVA'),'4');assert.equal(run("store.agenda.filter(e=>e.regla==='cita_afore').length"),1);assert.equal(run("agendaPrioritariaDashboard().filter(e=>e.regla==='cita_afore').length"),1);
run("store.clientes[0].fechaBiometrica=sumarDiasISO(fechaISOLocal(new Date()),6);sincronizarCitaAfore(store.clientes[0])");assert.equal(run("agendaPrioritariaDashboard().filter(e=>e.regla==='cita_afore').length"),1);run("store.clientes[0].fechaBiometrica=sumarDiasISO(fechaISOLocal(new Date()),7);sincronizarCitaAfore(store.clientes[0])");assert.equal(run("agendaPrioritariaDashboard().filter(e=>e.regla==='cita_afore').length"),0);assert.equal(run("store.agenda.filter(e=>e.regla==='cita_afore').length"),1);
run("store.clientes[0].fechaAltaAfore='2026-09-01';store.clientes[0].fechaSolicitudManual='2026-12-01'");assert.equal(run('fechaSolicitudCliente(store.clientes[0])'),'2026-10-16');run("store.clientes[0].fechaAltaAfore=''");assert.equal(run('etiquetaSolicitudCliente(store.clientes[0])'),'Confirmar fecha de alta');
run("actualizarSidebarSesion();navigate('asesores')");assert.equal(d.getElementById('nav-admin-section').style.display,'');assert(d.querySelector('[data-page=servicios]').hidden);assert(d.body.textContent.includes('Efectividad'));
run("navigate('contratos');selectedClienteId='test-client';onContratoClienteChange();setVal('ct-fecha','01/09/2026');actualizarFechaPagare()");assert.equal(d.getElementById('ct-pagare-fecha').value,'31/10/2026');assert(d.getElementById('ct-oficina'));
console.log('PASS: repeated editor opens, BBVA fields, appointment creation and rescheduling, 7-day boundary, alta+45 calculation, administrator access and pagaré+60.');dom.window.close();})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
