import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
function allowedOrigin(origin:string){return origin==='https://jeanmaxx.github.io'||origin==='http://localhost:8000'||origin==='http://127.0.0.1:8000'||/^https:\/\/[a-z0-9-]+\.pages\.dev$/i.test(origin)}
function corsHeaders(req:Request){const origin=req.headers.get('origin')||'';return {'Access-Control-Allow-Origin':allowedOrigin(origin)?origin:'https://jeanmaxx.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json','Vary':'Origin'}}
function respond(req:Request,status:number,payload:Record<string,unknown>){return new Response(JSON.stringify(payload),{status,headers:corsHeaders(req)})}
function validPassword(password:string){return password.length>=8&&/[A-Z]/.test(password)&&/[a-z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders(req)});if(req.method!=='POST')return respond(req,405,{error:'Método no permitido'});try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,authorization=req.headers.get('Authorization');if(!authorization)return respond(req,401,{error:'Sesión requerida'});
 const callerClient=createClient(url,anon,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}}),{data:authData,error:authError}=await callerClient.auth.getUser();if(authError||!authData.user)return respond(req,401,{error:'Sesión inválida'});
 const admin=createClient(url,service,{auth:{persistSession:false}});const {data:caller,error:callerError}=await admin.from('profiles').select('id,organization_id,role,active').eq('id',authData.user.id).single();if(callerError||!caller||caller.active!==true)return respond(req,403,{error:'Cuenta interna no autorizada'});const {data:tenant}=await admin.from('platform_tenants').select('status,suspension_reason').eq('organization_id',caller.organization_id).maybeSingle();if(tenant&&['suspended','cancelled'].includes(String(tenant.status)))return respond(req,403,{error:tenant.status==='cancelled'?'El servicio de esta organización está cancelado':('El servicio de esta organización está suspendido'+(tenant.suspension_reason?': '+tenant.suspension_reason:''))});const {data:moduleAllowed,error:moduleError}=await admin.rpc('organization_module_allowed',{target_org:caller.organization_id,module_name:'collaborators'});if(moduleError)throw moduleError;if(moduleAllowed!==true)return respond(req,403,{error:'El módulo de Colaboradores no está incluido en el plan de esta organización'});if(!['advisor','admin','tech_admin'].includes(caller.role))return respond(req,403,{error:'No tienes permiso para gestionar colaboradores'});
 const body=await req.json().catch(()=>({})),action=String(body.action||'list');
 if(action==='content_list'||action==='content_update'){
  if(!['admin','tech_admin'].includes(caller.role))return respond(req,403,{error:'Solo administración puede editar la guía institucional'});
  if(action==='content_list'){const {data,error}=await admin.from('collaborator_guide_content').select('*').eq('organization_id',caller.organization_id).order('sort_order');if(error)throw error;return respond(req,200,{ok:true,items:data||[]})}
  const slug=String(body.slug||'').trim();if(!/^[a-z0-9_-]+$/.test(slug))return respond(req,400,{error:'Identificador inválido'});const record={organization_id:caller.organization_id,slug,title:String(body.title||'').trim(),subtitle:String(body.subtitle||'').trim(),icon:String(body.icon||'▤').trim().slice(0,4),body:String(body.body||''),source_label:String(body.sourceLabel||'').trim(),source_url:String(body.sourceUrl||'').trim(),sort_order:Number(body.sortOrder)||100,active:body.active!==false,updated_at:new Date().toISOString(),updated_by:caller.id};if(!record.title)return respond(req,400,{error:'El título es obligatorio'});const {data,error}=await admin.from('collaborator_guide_content').upsert(record,{onConflict:'organization_id,slug'}).select('*').single();if(error)throw error;return respond(req,200,{ok:true,item:data});
 }
 if(!['list','upsert','deactivate','delete_account'].includes(action))return respond(req,400,{error:'Acción inválida'});
 let q=admin.from('collaborators').select('id,name,advisor_id,active,payload').eq('organization_id',caller.organization_id);if(caller.role==='advisor')q=q.eq('advisor_id',caller.id);const {data:collaborators,error:collaboratorsError}=await q.order('name');if(collaboratorsError)throw collaboratorsError;
 if(action==='list'){const ids=(collaborators||[]).map(c=>c.id);let accounts:any[]=[];if(ids.length){const {data,error}=await admin.from('collaborator_accounts').select('user_id,collaborator_id,email,active,created_at,updated_at').eq('organization_id',caller.organization_id).in('collaborator_id',ids);if(error)throw error;accounts=data||[]}const by=new Map(accounts.map(a=>[a.collaborator_id,a]));return respond(req,200,{ok:true,collaborators:(collaborators||[]).map(c=>{const a=by.get(c.id);return{collaboratorId:c.id,name:c.name,advisorId:c.advisor_id,collaboratorActive:c.active!==false,email:a?.email||c.payload?.email||'',profileEmail:c.payload?.email||'',birthDate:c.payload?.fechaNacimiento||'',accountActive:a?.active===true,hasAccount:Boolean(a),userId:a?.user_id||null}})})}
 const collaboratorId=String(body.collaboratorId||'').trim();if(!collaboratorId)return respond(req,400,{error:'Falta el colaborador'});const collaborator=(collaborators||[]).find(c=>c.id===collaboratorId);if(!collaborator)return respond(req,403,{error:'El colaborador no pertenece a tu ámbito de gestión'});const {data:existing,error:existingError}=await admin.from('collaborator_accounts').select('user_id,email,active').eq('organization_id',caller.organization_id).eq('collaborator_id',collaboratorId).maybeSingle();if(existingError)throw existingError;
 if(action==='delete_account'){if(existing?.user_id){const {error}=await admin.auth.admin.deleteUser(existing.user_id);if(error)throw error}else await admin.from('collaborator_accounts').delete().eq('organization_id',caller.organization_id).eq('collaborator_id',collaboratorId);return respond(req,200,{ok:true,deleted:true})}
 if(action==='deactivate'){if(!existing)return respond(req,404,{error:'El colaborador todavía no tiene cuenta'});const {error}=await admin.from('collaborator_accounts').update({active:false}).eq('user_id',existing.user_id);if(error)throw error;return respond(req,200,{ok:true,active:false})}
 const requestedEmail=Object.prototype.hasOwnProperty.call(body,'email')?String(body.email||'').trim().toLowerCase():String(existing?.email||collaborator.payload?.email||'').trim().toLowerCase(),password=String(body.password||''),active=body.active!==false;if(!requestedEmail)return respond(req,400,{error:'El correo es obligatorio'});if(!existing&&!validPassword(password))return respond(req,400,{error:'La contraseña temporal debe tener al menos 8 caracteres, mayúscula, minúscula, número y símbolo'});if(password&&!validPassword(password))return respond(req,400,{error:'La nueva contraseña no cumple los requisitos'});if(active&&collaborator.active===false)return respond(req,400,{error:'Primero reactiva al colaborador en el CRM'});
 let userId=existing?.user_id||'',createdNew=false;if(!userId){const {data,error}=await admin.auth.admin.createUser({email:requestedEmail,password,email_confirm:true,user_metadata:{portal:'collaborator',collaborator_id:collaboratorId,full_name:collaborator.name}});if(error)throw error;userId=data.user.id;createdNew=true}else{const attrs:Record<string,unknown>={email:requestedEmail,user_metadata:{portal:'collaborator',collaborator_id:collaboratorId,full_name:collaborator.name}};if(password)attrs.password=password;const {error}=await admin.auth.admin.updateUserById(userId,attrs);if(error)throw error}
 const {error:accountError}=await admin.from('collaborator_accounts').upsert({user_id:userId,organization_id:caller.organization_id,collaborator_id:collaboratorId,email:requestedEmail,active,created_by:existing?undefined:caller.id},{onConflict:'user_id'});if(accountError){if(createdNew)await admin.auth.admin.deleteUser(userId);throw accountError}
 return respond(req,200,{ok:true,userId,email:requestedEmail,active});
}catch(error){const message=error instanceof Error?error.message:'Error inesperado';return respond(req,400,{error:message})}});