import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
function allowedOrigin(origin:string){return origin==='https://jeanmaxx.github.io'||origin==='http://localhost:8000'||origin==='http://127.0.0.1:8000'||/^https:\/\/[a-z0-9-]+\.pages\.dev$/i.test(origin)}
function corsHeaders(req:Request){const origin=req.headers.get('origin')||'';return {'Access-Control-Allow-Origin':allowedOrigin(origin)?origin:'https://jeanmaxx.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json','Vary':'Origin'}}
function respond(req:Request,status:number,payload:Record<string,unknown>){return new Response(JSON.stringify(payload),{status,headers:corsHeaders(req)})}
const upper=(v:unknown)=>String(v??'').trim().toLocaleUpperCase('es-MX');const text=(v:unknown)=>String(v??'').trim();
function numberValue(v:unknown){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function initialStatus(s:string){if(s==='asesoria_pension')return'pensiones';if(s==='correccion_imss')return'correccion_imss';return'semanas'}
function portalPhase(p:any){const v=Number(p?.portalFase||1);return Number.isFinite(v)?Math.max(1,Math.min(5,Math.trunc(v))):1}
function serializeLead(row:any,guideSteps:any={}){const p=row.payload||{};return{id:row.id,name:row.name,phone:row.phone||'',curp:row.curp||'',serviceId:row.service_id||'retiro_desempleo',internalStatus:row.status,createdAt:row.created_at,updatedAt:row.updated_at,phase:portalPhase(p),steps:p.portalPasos||{},guideSteps:guideSteps||{},honorariosManejados:p.honorariosManejados??'',city:p.ciudad||'',afore:p.afore||'',aforeMovil:p.aforeMovil||'',bank:p.banco||'',bankLevel4:p.cuentaNivel4||'',notes:p.notas||'',waitingSignatureConfirmation:p.portalPendienteConfirmacionFirma===true}}
function collaboratorCommission(c:any,col:any){const p=c.payload||{},base=Number(p.comision??p.comisionCalc??0)||0,pct=Number(p.colPct??col?.payload?.pctComision??0)||0;return Math.round(base*(pct/100)*100)/100}
function paymentCollected(p:any){const s=String(p?.estadoPago||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return['cobrado','pagado','recibido','liquidado'].some(x=>s.includes(x))}
function stageRank(stage:string){const o=['generando_contrato','contrato_firmas','contrato_firmado','dado_alta','afore_actualizada','solicitud_realizada','solicitud_rechazada','deposito_recibido','honorarios_recibidos','concluido'];const i=o.indexOf(stage);return i<0?0:i}
function retirementProgress(stage:string,p:any){const r=stageRank(stage),hasAppointment=Boolean(p.fechaBiometrica||p.fechaCitaAfore||p.citaAforeFecha||p.horaBiometrica||p.horaCitaAfore||p.sucursalAfore);const done:any={6:r>=stageRank('dado_alta'),7:hasAppointment||r>=stageRank('afore_actualizada'),8:r>=stageRank('afore_actualizada'),9:r>=stageRank('solicitud_realizada'),10:r>=stageRank('deposito_recibido'),11:r>=stageRank('honorarios_recibidos')};let current=11;for(let s=6;s<=11;s++){if(!done[s]){current=s;break}}return{current,done,rejected:stage==='solicitud_rechazada'}}
function safeHistory(p:any){const allowed=new Set(['etapa','agenda','contrato','fecha','colaborador']),entries=Array.isArray(p?.historial)?p.historial:[];return entries.filter((h:any)=>allowed.has(String(h?.tipo||''))).slice(-14).map((h:any)=>({type:String(h?.tipo||''),text:String(h?.texto||''),date:String(h?.fecha||'')}))}
function latestContract(p:any){const v=Array.isArray(p?.historialContratos)?p.historialContratos.filter((x:any)=>x?.docxPath):[];v.sort((a:any,b:any)=>String(b?.fecha||'').localeCompare(String(a?.fecha||'')));const x=v[0];return x?{available:true,id:String(x.id||''),date:String(x.fecha||''),service:String(x.servicio||''),templateVersion:String(x.templateVersion||'')}:{available:false,id:'',date:'',service:'',templateVersion:''}}
function firstDate(p:any,fields:string[]){for(const field of fields){const value=String(p?.[field]||'').trim();if(value)return value}return''}
function serializeClient(row:any,col:any,guideSteps:any={}){const p=row.payload||{},serviceId=row.service_id||p.servicio||'retiro_desempleo',progress=serviceId==='retiro_desempleo'?retirementProgress(row.stage,p):{current:6,done:{6:false,7:false,8:false,9:false,10:false,11:false},rejected:false},source=p.prospectoOrigen||{},collected=paymentCollected(p);return{id:row.id,name:row.name,phone:row.phone||p.telefono||'',curp:row.curp||p.curp||'',serviceId,stage:row.stage,createdAt:row.created_at,updatedAt:row.updated_at,progress,guideSteps:guideSteps||{},afore:p.afore||source.afore||'',appointment:{date:String(p.fechaBiometrica||p.fechaCitaAfore||p.citaAforeFecha||''),time:String(p.horaBiometrica||p.horaCitaAfore||p.citaAforeHora||''),branch:String(p.sucursalAfore||p.direccionCitaAfore||p.citaAforeSucursal||'')},contract:latestContract(p),history:safeHistory(p),commission:collaboratorCommission(row,col),paymentStatus:String(p.estadoPago||'Pendiente'),collected,expectedPaymentDate:firstDate(p,['fechaRetiroEstimada','fechaSolicitudManual','fechaSolicitudRealizada','fechaAltaAfore']),paidDate:firstDate(p,['fechaCierre','fechaHonorarios','fechaDeposito','fechaRetiroReal']),archived:row.archived===true,discarded:row.discarded===true}}
function bytesToBase64(bytes:Uint8Array){let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(binary)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders(req)});if(req.method!=='POST')return respond(req,405,{error:'Método no permitido'});try{
const body=await req.json().catch(()=>({})),action=String(body.action||'bootstrap');if(!['bootstrap','create_prospect','update_prospect','complete_step','get_contract','record_contract_download','guide_toggle','guide_reset'].includes(action))return respond(req,400,{error:'Acción inválida'});const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,authorization=req.headers.get('Authorization');if(!authorization)return respond(req,401,{error:'Sesión requerida'});const callerClient=createClient(url,anon,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}}),{data:authData,error:authError}=await callerClient.auth.getUser();if(authError||!authData.user)return respond(req,401,{error:'Sesión inválida'});const admin=createClient(url,service,{auth:{persistSession:false}});const {data:account,error:accountError}=await admin.from('collaborator_accounts').select('user_id,organization_id,collaborator_id,email,active').eq('user_id',authData.user.id).maybeSingle();if(accountError)throw accountError;if(!account||account.active!==true)return respond(req,403,{error:'Tu acceso al Portal de Colaboradores no está activo'});const expectedTenantSlug=String(body.tenantSlug||'').trim().toLowerCase();const {data:organization,error:organizationError}=await admin.from('organizations').select('id,name,slug').eq('id',account.organization_id).maybeSingle();if(organizationError)throw organizationError;if(!organization)return respond(req,403,{error:'La organización de esta cuenta ya no está disponible'});if(expectedTenantSlug&&String(organization.slug||'').toLowerCase()!==expectedTenantSlug)return respond(req,403,{error:'Esta cuenta no corresponde a la organización de este enlace'});const {data:tenant}=await admin.from('platform_tenants').select('status,suspension_reason').eq('organization_id',account.organization_id).maybeSingle();if(tenant&&['suspended','cancelled'].includes(String(tenant.status)))return respond(req,403,{error:tenant.status==='cancelled'?'El servicio de esta organización está cancelado':('El servicio de esta organización está suspendido'+(tenant.suspension_reason?': '+tenant.suspension_reason:''))});const {data:moduleAllowed,error:moduleError}=await admin.rpc('organization_module_allowed',{target_org:account.organization_id,module_name:'collaborators'});if(moduleError)throw moduleError;if(moduleAllowed!==true)return respond(req,403,{error:'El Portal de Colaboradores no está incluido en el plan de esta organización'});const {data:collaborator,error:collabError}=await admin.from('collaborators').select('id,name,advisor_id,active,payload').eq('organization_id',account.organization_id).eq('id',account.collaborator_id).single();if(collabError||!collaborator||collaborator.active===false)return respond(req,403,{error:'El colaborador está inactivo'});if(!collaborator.advisor_id)return respond(req,409,{error:'Tu cuenta todavía no tiene un asesor asignado'});

const appendActivity=async(actionName:string,leadId:string|null,detail:Record<string,unknown>)=>{const {error}=await admin.from('collaborator_portal_activity').insert({organization_id:account.organization_id,collaborator_id:collaborator.id,actor_user_id:authData.user!.id,lead_id:leadId,action:actionName,detail});if(error)console.error('activity',error.message)};
const getOwnClient=async(clientId:string)=>{const {data,error}=await admin.from('clients').select('id,name,phone,curp,service_id,stage,archived,discarded,payload,created_at,updated_at,collaborator_id').eq('organization_id',account.organization_id).eq('id',clientId).eq('collaborator_id',collaborator.id).maybeSingle();if(error)throw error;return data};
const appendClientHistory=async(client:any,message:string)=>{const event={tipo:'colaborador',texto:message,fecha:new Date().toISOString(),usuario:`Colaborador: ${collaborator.name}`,usuarioId:authData.user!.id};const {error}=await admin.rpc('append_collaborator_client_history',{p_organization_id:account.organization_id,p_client_id:client.id,p_collaborator_id:collaborator.id,p_event:event});if(error)throw error};
if(action==='bootstrap'){
 const [{data:advisor},{data:services},{data:leads,error:leadsError},{data:clients,error:clientsError},{data:content,error:contentError},{data:progress,error:progressError}]=await Promise.all([
  admin.from('profiles').select('id,full_name').eq('id',collaborator.advisor_id).maybeSingle(),
  admin.from('services').select('id,name,active').eq('organization_id',account.organization_id).eq('active',true).order('name'),
  admin.from('leads').select('id,name,phone,curp,service_id,status,payload,created_at,updated_at').eq('organization_id',account.organization_id).eq('collaborator_id',collaborator.id).order('created_at',{ascending:false}),
  admin.from('clients').select('id,name,phone,curp,service_id,stage,archived,discarded,payload,created_at,updated_at').eq('organization_id',account.organization_id).eq('collaborator_id',collaborator.id).order('updated_at',{ascending:false}),
  admin.from('collaborator_guide_content').select('slug,title,subtitle,icon,body,source_label,source_url,sort_order').eq('organization_id',account.organization_id).eq('active',true).order('sort_order'),
  admin.from('collaborator_guide_progress').select('record_type,record_id,steps').eq('organization_id',account.organization_id).eq('collaborator_id',collaborator.id)
 ]);if(leadsError)throw leadsError;if(clientsError)throw clientsError;if(contentError)throw contentError;if(progressError)throw progressError;
 const guide=new Map((progress||[]).map((x:any)=>[`${x.record_type}:${x.record_id}`,x.steps||{}]));const leadRows=leads||[],clientRows=clients||[],opportunities=leadRows.length+clientRows.length,converted=clientRows.length,effectiveness=opportunities?Math.round(converted/opportunities*1000)/10:0;let collected=0,pending=0;for(const client of clientRows){const amount=collaboratorCommission(client,collaborator);if(paymentCollected(client.payload))collected+=amount;else pending+=amount}
 return respond(req,200,{ok:true,organization:{id:organization.id,name:organization.name,slug:organization.slug},collaborator:{id:collaborator.id,name:collaborator.name,nombres:collaborator.payload?.nombres||'',apellidos:collaborator.payload?.apellidos||'',email:account.email||collaborator.payload?.email||'',birthDate:collaborator.payload?.fechaNacimiento||'',city:collaborator.payload?.ciudad||'',pctComision:collaborator.payload?.pctComision??null},advisor:{id:advisor?.id||collaborator.advisor_id,name:advisor?.full_name||'Asesor asignado'},services:(services||[]).map(s=>({id:s.id,name:s.name})),dashboard:{opportunities,converted,effectiveness,collected:Math.round(collected*100)/100,pending:Math.round(pending*100)/100},prospects:leadRows.map((r:any)=>serializeLead(r,guide.get(`lead:${r.id}`)||{})),clients:clientRows.filter((c:any)=>c.discarded!==true).map((c:any)=>serializeClient(c,collaborator,guide.get(`client:${c.id}`)||{})),guideContent:content||[]})
}
if(action==='guide_toggle'||action==='guide_reset'){
 const recordType=String(body.recordType||'');const recordId=text(body.recordId);if(!['lead','client'].includes(recordType)||!recordId)return respond(req,400,{error:'Selecciona un prospecto o cliente'});const table=recordType==='lead'?'leads':'clients';const {data:owned,error:ownedError}=await admin.from(table).select('id').eq('organization_id',account.organization_id).eq('id',recordId).eq('collaborator_id',collaborator.id).maybeSingle();if(ownedError)throw ownedError;if(!owned)return respond(req,404,{error:'El registro no pertenece a tu cartera'});
 const {data:existing,error:existingError}=await admin.from('collaborator_guide_progress').select('steps').eq('organization_id',account.organization_id).eq('collaborator_id',collaborator.id).eq('record_type',recordType).eq('record_id',recordId).maybeSingle();if(existingError)throw existingError;let steps:any={...(existing?.steps||{})};
 if(action==='guide_reset')steps={};else{const step=Math.trunc(Number(body.step));if(step<1||step>11)return respond(req,400,{error:'Paso inválido'});steps[String(step)]={checked:body.checked!==false,at:new Date().toISOString()}}
 const {error}=await admin.from('collaborator_guide_progress').upsert({organization_id:account.organization_id,collaborator_id:collaborator.id,record_type:recordType,record_id:recordId,steps,updated_at:new Date().toISOString()},{onConflict:'organization_id,collaborator_id,record_type,record_id'});if(error)throw error;await appendActivity(action==='guide_reset'?'guide_reset':'guide_step_toggled',recordType==='lead'?recordId:null,{recordType,recordId,step:body.step??null,checked:body.checked??null});return respond(req,200,{ok:true,steps})
}
if(action==='get_contract'||action==='record_contract_download'){const clientId=text(body.clientId);if(!clientId)return respond(req,400,{error:'Falta el cliente'});const client=await getOwnClient(clientId);if(!client)return respond(req,404,{error:'El cliente no está disponible'});const p=client.payload||{},versions=Array.isArray(p.historialContratos)?p.historialContratos.filter((x:any)=>x?.docxPath):[];versions.sort((a:any,b:any)=>String(b?.fecha||'').localeCompare(String(a?.fecha||'')));const version=versions[0];if(!version)return respond(req,404,{error:'Todavía no hay un contrato guardado para este cliente'});if(action==='record_contract_download'){await appendClientHistory(client,`Contrato descargado en PDF por ${collaborator.name} desde Portal de Colaboradores`);await appendActivity('contract_pdf_downloaded',null,{clientId,contractId:version.id});return respond(req,200,{ok:true})}const {data:file,error:fileError}=await admin.storage.from('crm-contracts').download(version.docxPath);if(fileError||!file)throw fileError||new Error('No se pudo recuperar el contrato');const bytes=new Uint8Array(await file.arrayBuffer());await appendClientHistory(client,`Contrato consultado por ${collaborator.name} desde Portal de Colaboradores`);await appendActivity('contract_viewed',null,{clientId,contractId:version.id});return respond(req,200,{ok:true,contract:{id:String(version.id||''),date:String(version.fecha||''),fileName:`Contrato-${String(client.name||'cliente').replace(/[^A-Za-z0-9ÁÉÍÓÚÜÑáéíóúüñ -]+/g,'').trim().replace(/\s+/g,'-')}.docx`,mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',base64:bytesToBase64(bytes)}})}
if(action==='create_prospect'){const name=upper(body.name),phone=text(body.phone),curp=upper(body.curp);if(!name||!phone||!curp)return respond(req,400,{error:'Nombre, teléfono y CURP son obligatorios'});const serviceId=text(body.serviceId)||'retiro_desempleo',now=new Date().toISOString(),id=`lead_col_${Date.now()}_${crypto.randomUUID().slice(0,8)}`,history=[{tipo:'colaborador',texto:`Prospecto enviado por ${collaborator.name}`,fecha:now,usuario:`Colaborador: ${collaborator.name}`,usuarioId:authData.user.id}],payload={id,nombre:name,telefono:phone,curp,servicio:serviceId,estado:initialStatus(serviceId),asesorId:collaborator.advisor_id,colaboradorId:collaborator.id,fuente:'de_colaborador',fechaInicio:now,fechaCaptura:now,fechaRegistro:now,portalColaborador:true,portalFase:1,portalPasos:{},portalCreadoPor:collaborator.name,honorariosManejados:numberValue(body.honorariosManejados),ciudad:upper(body.city),afore:upper(body.afore),aforeMovil:text(body.aforeMovil),banco:upper(body.bank),cuentaNivel4:text(body.bankLevel4),notas:text(body.notes),historial:history};const {data,error}=await admin.from('leads').insert({organization_id:account.organization_id,id,advisor_id:collaborator.advisor_id,legacy_advisor_id:null,collaborator_id:collaborator.id,name,phone,curp,service_id:serviceId,status:initialStatus(serviceId),archive_type:null,recontact_date:null,payload,created_at:now}).select('id,name,phone,curp,service_id,status,payload,created_at,updated_at').single();if(error)throw error;await appendActivity('prospect_created',id,{name,curp,serviceId});return respond(req,200,{ok:true,prospect:serializeLead(data)})}
const leadId=text(body.leadId);if(!leadId)return respond(req,400,{error:'Falta el prospecto'});const {data:lead,error:leadError}=await admin.from('leads').select('id,name,phone,curp,service_id,status,payload,created_at,updated_at,advisor_id,collaborator_id').eq('organization_id',account.organization_id).eq('id',leadId).eq('collaborator_id',collaborator.id).maybeSingle();if(leadError)throw leadError;if(!lead)return respond(req,404,{error:'El prospecto ya no está disponible o fue convertido a cliente'});
if(action==='update_prospect'){const name=Object.prototype.hasOwnProperty.call(body,'name')?upper(body.name):lead.name,phone=Object.prototype.hasOwnProperty.call(body,'phone')?text(body.phone):(lead.phone||''),curp=Object.prototype.hasOwnProperty.call(body,'curp')?upper(body.curp):(lead.curp||'');if(!name||!phone||!curp)return respond(req,400,{error:'Nombre, teléfono y CURP no pueden quedar vacíos'});const serviceId=Object.prototype.hasOwnProperty.call(body,'serviceId')?(text(body.serviceId)||lead.service_id):lead.service_id,existing=lead.payload||{},history=Array.isArray(existing.historial)?[...existing.historial]:[];history.push({tipo:'colaborador',texto:`Información actualizada por ${collaborator.name}`,fecha:new Date().toISOString(),usuario:`Colaborador: ${collaborator.name}`,usuarioId:authData.user.id});const payload={...existing,nombre:name,telefono:phone,curp,servicio:serviceId,honorariosManejados:Object.prototype.hasOwnProperty.call(body,'honorariosManejados')?numberValue(body.honorariosManejados):existing.honorariosManejados,ciudad:Object.prototype.hasOwnProperty.call(body,'city')?upper(body.city):existing.ciudad,afore:Object.prototype.hasOwnProperty.call(body,'afore')?upper(body.afore):existing.afore,aforeMovil:Object.prototype.hasOwnProperty.call(body,'aforeMovil')?text(body.aforeMovil):existing.aforeMovil,banco:Object.prototype.hasOwnProperty.call(body,'bank')?upper(body.bank):existing.banco,cuentaNivel4:Object.prototype.hasOwnProperty.call(body,'bankLevel4')?text(body.bankLevel4):existing.cuentaNivel4,notas:Object.prototype.hasOwnProperty.call(body,'notes')?text(body.notes):existing.notas,historial:history};const {data,error}=await admin.from('leads').update({name,phone,curp,service_id:serviceId,payload}).eq('organization_id',account.organization_id).eq('id',lead.id).eq('collaborator_id',collaborator.id).select('id,name,phone,curp,service_id,status,payload,created_at,updated_at').single();if(error)throw error;await appendActivity('prospect_updated',lead.id,{fields:'portal'});return respond(req,200,{ok:true,prospect:serializeLead(data)})}
const step=Math.trunc(Number(body.step));if(step<1||step>5)return respond(req,400,{error:'Fase inválida'});const existing=lead.payload||{},current=portalPhase(existing);if(step!==current)return respond(req,409,{error:`Primero completa la fase ${current}`});const now=new Date().toISOString(),steps={...(existing.portalPasos||{}),[String(step)]:{completado:true,fecha:now,por:collaborator.name}},labels=['','Revisión de elegibilidad (CURP)','Documentación para contrato','Descarga de AFORE Móvil','Revisión de cuenta bancaria Nivel 4','Firma de contrato'],history=Array.isArray(existing.historial)?[...existing.historial]:[];history.push({tipo:'colaborador',texto:`${collaborator.name} marcó realizada: ${labels[step]}`,fecha:now,usuario:`Colaborador: ${collaborator.name}`,usuarioId:authData.user.id});const payload={...existing,portalPasos:steps,portalFase:step<5?step+1:5,historial,portalPendienteConfirmacionFirma:step===5?true:existing.portalPendienteConfirmacionFirma};const {data,error}=await admin.from('leads').update({payload}).eq('organization_id',account.organization_id).eq('id',lead.id).eq('collaborator_id',collaborator.id).select('id,name,phone,curp,service_id,status,payload,created_at,updated_at').single();if(error)throw error;await appendActivity('step_completed',lead.id,{step,label:labels[step]});return respond(req,200,{ok:true,prospect:serializeLead(data)})
}catch(error){const message=error instanceof Error?error.message:'Error inesperado';return respond(req,400,{error:message})}});